name: Build Site

env:
  GITHUB_WORKSPACE: /home/runner/work/parkersprouse.github.io/parkersprouse.github.io

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  configure_build_deploy:
    runs-on: ubuntu-latest
    steps:
      # STEP 1 #
      - name: Checkout Repo
        uses: actions/checkout@v4

      # STEP 2 #
      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      # STEP 3 #
      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: true
          version: 9

      # STEP 4 #
      - name: Build Site
        run: pnpm run build

      # STEP 5 #
      - name: Capture Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: ${{ env.GITHUB_WORKSPACE }}/dist

      # STEP 6 #
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: deployed
          folder: ${{ env.GITHUB_WORKSPACE }}/dist
          commit-message: Site built successfully - deploying
