# This Action isn't currently in use - use the `pnpm run deploy` script instead

name: Build Site

on:
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write
  pages: write

# Allow one concurrent deployment
concurrency:
  cancel-in-progress: true
  group: 'pages'

jobs:
  configure_build_deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # STEP 1 #
      - name: Checkout Repo
        uses: actions/checkout@v4

      # STEP 2 #
      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      # STEP 3 #
      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: true
          version: 9

      # STEP 4 #
      - name: Build Site
        run: pnpm run build

      # STEP 5 #
      - name: Configure Pages
        uses: actions/configure-pages@v5

      # STEP 6 #
      - name: Upload artifact packaged for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      # STEP 7 #
      - name: Deploy artifact to Pages
        id: deployment
        uses: actions/deploy-pages@v4
